import { describe, it, expect, beforeEach } from 'vitest'
import {
  getPreviewLuaSyncKey,
  logLogicBoardCompileFailure,
  resolvePreviewMainLua,
  resolvePreviewMainLuaWithStatus,
} from './preview-restore'
import type { Action } from '../store/editor-store'
import { clearLogicCompileCache } from './logic-board/logic-compile-service'
import { clearProjectWorkbenchCache } from './project-health'
import { BLANK_MAIN_LUA } from './project'

function makeProject(overrides: Record<string, unknown> = {}) {
  return {
    projectName: 'T',
    version: '1',
    activeSceneId: 'a',
    mainScriptPath: 'scripts/main.lua',
    targetFPS: 60,
    entities: {},
    scenes: {},
    logicBoards: [],
    ...overrides,
  }
}

describe('resolvePreviewMainLua', () => {
  beforeEach(() => {
    clearLogicCompileCache()
    clearProjectWorkbenchCache()
  })

  it('prefers openScripts content for mainScriptPath when no logic boards', () => {
    const project = makeProject()
    const lua = resolvePreviewMainLua({
      project: project as never,
      openScripts: [{ path: 'scripts/main.lua', content: '-- from tab', isDirty: false }],
    })
    expect(lua).toContain('-- from tab')
    expect(lua).toContain('rawset(_G, "tick", __artcade_user_tick)')
  })

  it('prefers compiled logic boards over non-dirty main.lua tab stub', () => {
    const project = makeProject({
      logicBoards: [{
        boardId: 'b1',
        target: { type: 'object_type', objectTypeId: 'Player' },
        events: [],
      }],
    })
    const lua = resolvePreviewMainLua({
      project: project as never,
      openScripts: [{
        path: 'scripts/main.lua',
        content: BLANK_MAIN_LUA,
        isDirty: false,
      }],
    })
    expect(lua).toContain('AUTO-GENERATED by ArtCade Logic Board compiler')
    expect(lua).not.toBe(BLANK_MAIN_LUA)
  })

  it('combines a dirty manual main script with logic boards', () => {
    const project = makeProject({
      logicBoards: [{
        boardId: 'b1',
        target: { type: 'object_type', objectTypeId: 'Player' },
        events: [],
      }],
    })
    const lua = resolvePreviewMainLua({
      project: project as never,
      openScripts: [{
        path: 'scripts/main.lua',
        content: '-- hand-edited',
        isDirty: true,
      }],
    })
    expect(lua).toContain('-- ARTCADE: LOGIC BOARD')
    expect(lua).toContain('-- hand-edited')
    expect(lua).toContain('-- ARTCADE: BOOTSTRAP')
  })

  it('compiles logic boards when main script tab is missing', () => {
    const project = makeProject({
      logicBoards: [{
        boardId: 'b1',
        target: { type: 'object_type', objectTypeId: 'Player' },
        events: [],
      }],
    })
    const lua = resolvePreviewMainLua({ project: project as never, openScripts: [] })
    expect(lua).toContain('AUTO-GENERATED by ArtCade Logic Board compiler')
  })

  it('falls back to blank main lua when nothing else is available', () => {
    const project = makeProject({ mainScriptPath: '', logicBoards: [] })
    const lua = resolvePreviewMainLua({ project: project as never, openScripts: [] })
    expect(lua).toContain('-- main.lua  (ArtCade V2)')
    expect(lua).toContain('function tick(dt)')
    expect(lua).toContain('-- ARTCADE: BOOTSTRAP')
  })

  it('does not throw when logic boards fail to compile', () => {
    const project = makeProject({
      logicBoards: [{
        boardId: 'g1',
        target: { type: 'global' },
        events: [{
          id: 'e1',
          enabled: true,
          trigger: { type: 'onMouseInput', button: 'right', eventType: 'pressed' },
          actions: [{ type: 'clickToDestroy', button: 'right', radius: 32 }],
        }],
      }],
    })
    const input = {
      project: project as never,
      openScripts: [],
      projectPath: '/tmp/preview-fail.artcade',
    }
    const lua = resolvePreviewMainLua(input)
    expect(lua).toContain('-- main.lua  (ArtCade V2)')
    expect(lua).toContain('function tick(dt)')
    expect(lua).toContain('-- ARTCADE: BOOTSTRAP')
    const status = resolvePreviewMainLuaWithStatus(input)
    expect(status.compileError).toMatch(/entity rulesheets/)
  })

  it('uses last-good lua from cache when compile fails', () => {
    const key = '/tmp/preview-cache.artcade'
    const okProject = makeProject({
      logicBoards: [{
        boardId: 'b1',
        target: { type: 'object_type', objectTypeId: 'Player' },
        events: [],
      }],
    })
    const goodLua = resolvePreviewMainLua({
      project: okProject as never,
      openScripts: [],
      projectPath: key,
    })
    expect(goodLua).toContain('AUTO-GENERATED')

    const badProject = makeProject({
      logicBoards: [{
        boardId: 'g1',
        target: { type: 'global' },
        events: [{
          id: 'e1',
          enabled: true,
          trigger: { type: 'onMouseInput', button: 'right', eventType: 'pressed' },
          actions: [{ type: 'clickToDestroy', button: 'right', radius: 32 }],
        }],
      }],
    })
    const lua = resolvePreviewMainLua({
      project: badProject as never,
      openScripts: [],
      projectPath: key,
    })
    expect(lua).toBe(goodLua)
  })
})

describe('getPreviewLuaSyncKey', () => {
  it('ignores keystrokes on non-main script tabs', () => {
    const project = makeProject()
    const base = {
      project: project as never,
      projectPath: '/tmp/p',
      openScripts: [] as { path: string; content: string; isDirty: boolean }[],
    }
    const keyA = getPreviewLuaSyncKey({
      ...base,
      openScripts: [{ path: 'scripts/other.lua', content: 'a', isDirty: true }],
    })
    const keyB = getPreviewLuaSyncKey({
      ...base,
      openScripts: [{ path: 'scripts/other.lua', content: 'bbbb', isDirty: true }],
    })
    expect(keyA).toBe(keyB)
  })

  it('changes when the main script tab is dirty-edited', () => {
    const project = makeProject()
    const keyA = getPreviewLuaSyncKey({
      project: project as never,
      projectPath: '/tmp/p',
      openScripts: [{ path: 'scripts/main.lua', content: 'v1', isDirty: true }],
    })
    const keyB = getPreviewLuaSyncKey({
      project: project as never,
      projectPath: '/tmp/p',
      openScripts: [{ path: 'scripts/main.lua', content: 'v2', isDirty: true }],
    })
    expect(keyA).not.toBe(keyB)
  })
})

describe('logLogicBoardCompileFailure', () => {
  it('dispatches LOG and opens console when compile failed', () => {
    const actions: Action[] = []
    const dispatch = (a: Action) => actions.push(a)
    logLogicBoardCompileFailure(
      dispatch,
      'invalid rules',
      (message, level) => ({ id: 1, time: '', message, level }),
    )
    expect(actions).toEqual([
      { type: 'LOG', entry: { id: 1, time: '', message: expect.stringContaining('invalid rules'), level: 'error' } },
      { type: 'SET_CONSOLE_OPEN', open: true },
    ])
  })

  it('no-ops when compileError is null', () => {
    const actions: Action[] = []
    logLogicBoardCompileFailure(actions.push as never, null, () => ({ id: 0, time: '', message: '', level: 'info' }))
    expect(actions).toHaveLength(0)
  })
})
