import { describe, it, expect } from 'vitest'
import {
  logLogicBoardCompileFailure,
  resolvePreviewMainLua,
  resolvePreviewMainLuaWithStatus,
} from './preview-restore'
import type { Action } from '../store/editor-store'
import { BLANK_MAIN_LUA } from './project'

function makeProject(overrides: Record<string, unknown> = {}) {
  return {
    projectName: 'T',
    version: '1',
    activeSceneId: 'a',
    mainScriptPath: 'scripts/main.lua',
    targetFPS: 60,
    entities: {},
    scenes: {},
    logicBoards: [],
    ...overrides,
  }
}

describe('resolvePreviewMainLua', () => {
  it('prefers openScripts content for mainScriptPath', () => {
    const project = makeProject()
    const lua = resolvePreviewMainLua({
      project: project as never,
      openScripts: [{ path: 'scripts/main.lua', content: '-- from tab', isDirty: false }],
    })
    expect(lua).toBe('-- from tab')
  })

  it('compiles logic boards when main script tab is missing', () => {
    const project = makeProject({
      logicBoards: [{
        boardId: 'b1',
        target: { type: 'entity_class', className: 'Player' },
        events: [],
      }],
    })
    const lua = resolvePreviewMainLua({ project: project as never, openScripts: [] })
    expect(lua).toContain('AUTO-GENERATED by ArtCade Logic Board compiler')
  })

  it('falls back to blank main lua when nothing else is available', () => {
    const project = makeProject({ mainScriptPath: '', logicBoards: [] })
    const lua = resolvePreviewMainLua({ project: project as never, openScripts: [] })
    expect(lua).toBe(BLANK_MAIN_LUA)
  })

  it('does not throw when logic boards fail to compile', () => {
    const project = makeProject({
      logicBoards: [{
        boardId: 'g1',
        target: { type: 'global' },
        events: [{
          id: 'e1',
          enabled: true,
          trigger: { type: 'onMouseInput', button: 'right', eventType: 'pressed' },
          actions: [{ type: 'clickToDestroy', button: 'right', radius: 32 }],
        }],
      }],
    })
    const lua = resolvePreviewMainLua({ project: project as never, openScripts: [] })
    expect(lua).toBe(BLANK_MAIN_LUA)
    const status = resolvePreviewMainLuaWithStatus({ project: project as never, openScripts: [] })
    expect(status.compileError).toMatch(/entity rulesheets/)
  })
})

describe('logLogicBoardCompileFailure', () => {
  it('dispatches LOG and opens console when compile failed', () => {
    const actions: Action[] = []
    const dispatch = (a: Action) => actions.push(a)
    logLogicBoardCompileFailure(
      dispatch,
      'invalid rules',
      (message, level) => ({ id: 1, time: '', message, level }),
    )
    expect(actions).toEqual([
      { type: 'LOG', entry: { id: 1, time: '', message: expect.stringContaining('invalid rules'), level: 'error' } },
      { type: 'SET_CONSOLE_OPEN', open: true },
    ])
  })

  it('no-ops when compileError is null', () => {
    const actions: Action[] = []
    logLogicBoardCompileFailure(actions.push as never, null, () => ({ id: 0, time: '', message: '', level: 'info' }))
    expect(actions).toHaveLength(0)
  })
})
