import type { ProjectDoc, ScriptFile } from '../types'
import { BLANK_MAIN_LUA } from './project-factory'

export const LEGACY_GENERATED_LUA_MARKER = 'AUTO-GENERATED by ArtCade Logic Board compiler'
export const LEGACY_MAIN_LUA_MIGRATION_MESSAGE =
  '[Script] Legacy generated main.lua was reset. Logic Board code is now managed separately.'

export function resolveManualMainLua(
  project: ProjectDoc,
  openScripts: ReadonlyArray<ScriptFile>,
): string {
  return openScripts.find((script) => script.path === project.mainScriptPath)?.content
    ?? BLANK_MAIN_LUA
}

export function isLegacyGeneratedMainLua(source: string): boolean {
  return source.includes(LEGACY_GENERATED_LUA_MARKER)
}

/** Reset only pre-separation generated main scripts; preserve every manual source byte. */
export function migrateLegacyGeneratedMainLua(source: string): {
  content: string
  isDirty: boolean
  migrated: boolean
} {
  const migrated = isLegacyGeneratedMainLua(source)
  return {
    content: migrated ? BLANK_MAIN_LUA : source,
    isDirty: migrated,
    migrated,
  }
}
