import type { ProjectDoc, ScriptFile } from '../types'
import { BLANK_MAIN_LUA } from './project-factory'

export const LEGACY_GENERATED_LUA_MARKER = 'AUTO-GENERATED by ArtCade Logic Board compiler'
export const LEGACY_MAIN_LUA_MIGRATION_MESSAGE =
  '[Script] Legacy generated main.lua was reset. Logic Board code is now managed separately.'

export const COMPOSED_MAIN_LUA_MARKER = '-- ARTCADE: LOGIC BOARD'
export const MANUAL_BEGIN_MARKER = '-- ARTCADE: MANUAL_BEGIN'
export const MANUAL_END_MARKER = '-- ARTCADE: MANUAL_END'

export function resolveManualMainLua(
  project: ProjectDoc,
  openScripts: ReadonlyArray<ScriptFile>,
): string {
  return openScripts.find((script) => script.path === project.mainScriptPath)?.content
    ?? BLANK_MAIN_LUA
}

export function isLegacyGeneratedMainLua(source: string): boolean {
  return source.includes(LEGACY_GENERATED_LUA_MARKER)
}

export function isComposedMainLua(source: string): boolean {
  return source.includes(COMPOSED_MAIN_LUA_MARKER)
    || source.includes(MANUAL_BEGIN_MARKER)
}

/**
 * Recover the authoring "My Script" body from a ship-composed main.lua.
 * Disk may hold Logic Board + manual + bootstrap; the Script editor only edits manual.
 */
export function extractManualMainLua(source: string): string {
  const begin = source.indexOf(MANUAL_BEGIN_MARKER)
  const end = source.indexOf(MANUAL_END_MARKER)
  if (begin >= 0 && end > begin) {
    return source
      .slice(begin + MANUAL_BEGIN_MARKER.length, end)
      .replace(/^\r?\n/, '')
      .replace(/\r?\n$/, '')
  }
  if (isLegacyGeneratedMainLua(source) || isComposedMainLua(source)) {
    return BLANK_MAIN_LUA
  }
  return source
}

/** Reset only pre-separation generated main scripts; preserve every manual source byte. */
export function migrateLegacyGeneratedMainLua(source: string): {
  content: string
  isDirty: boolean
  migrated: boolean
} {
  if (isLegacyGeneratedMainLua(source)) {
    return { content: BLANK_MAIN_LUA, isDirty: true, migrated: true }
  }
  if (isComposedMainLua(source)) {
    return { content: extractManualMainLua(source), isDirty: false, migrated: false }
  }
  return { content: source, isDirty: false, migrated: false }
}
