// ---------------------------------------------------------------------------
// One-line catalog descriptions — shown under each entry in CatalogPicker.
// Plain language, no engine jargon; complements names.ts display names.
// ---------------------------------------------------------------------------

import type {
  LogicActionType,
  LogicCondition,
  LogicTriggerType,
} from '../../../types/logic-board'
import type { ComponentKind } from '../../../utils/logic-board/schema-registry'

const TRIGGER_DESCRIPTIONS: Record<LogicTriggerType, string> = {
  onStart: 'Once, when the scene starts',
  onSpawn: 'When an instance of this object is created',
  onUpdate: 'Every frame while the game runs — use sparingly',
  onCollision: 'Every frame while touching an object of the chosen type',
  onCollisionEnter: 'Once, when contact with the chosen type begins',
  onCollisionExit: 'Once, when contact with the chosen type ends',
  onTriggerEnter: 'When a tagged object enters this object\'s Sensor area',
  onTriggerExit: 'When a tagged object leaves this object\'s Sensor area',
  onAnimationEnd: 'When the current clip reaches its last frame',
  onAnimationStart: 'When a clip begins playing on this object',
  onAnimationFrame: 'When the clip reaches a specific frame number',
  onAnimationLoop: 'Each time a looping clip restarts from the first frame',
  onAnimationChange: 'When this object switches to the chosen clip',
  onDestroy: 'When an instance of this object is removed',
  onHealthDepleted: 'Once, when the object\'s HP drops to zero for the first time',
  onDamaged: 'Once per hit, when the object\'s HP decreases',
  onLeaveScreen: 'Once, when the object moves outside the camera view',
  onInput: 'When the player presses, holds or releases a key',
  onMouseInput: 'Click, press or release anywhere in the game',
  onObjectClick: 'When the player clicks this object',
  onObjectHoverEnter: 'When the pointer moves onto this object',
  onObjectHoverExit: 'When the pointer moves off this object',
  onMessage: 'When an Event Bus event is broadcast',
  onDialogMessage: 'When a dialog emits this message',
  onTimer: 'Every N seconds, or once after a delay',
}

const CONDITION_DESCRIPTIONS: Record<LogicCondition['type'], string> = {
  compareVariable: 'Compare a variable against a value',
  compareValues: 'Compare literals, variables, object properties, Component values, messages, or expressions',
  compareClass: 'The object is touching an object of a given type',
  isKeyDown: 'A key is currently held down',
  hasTag: 'The object has a given tag',
  compareDistance: 'Distance between two objects vs a value',
  isMouseOver: 'The pointer is near this object',
  raycastHit: 'A clear straight line exists to the target',
  chance: 'Passes randomly with the given probability',
  isTileAreaFree: 'No solid tile in the active tilemap occupies the area',
  isSpaceFree: 'Legacy name: checks solid tiles in the active tilemap',
  compareHealth: "Compare the object's health against a value",
  isPlatformerGrounded: 'The platformer body is standing on ground',
  compareCount: 'Number of live instances of an object type vs a value',
  entityExists: 'Check whether a specific object is still alive in the scene',
  compareVelocity: 'Compare velocity (x, y, or speed) against a value',
  comparePosition: 'Compare the x or y world position against a value',
  saveExists: 'Check whether a save file slot exists on disk',
  isDialogActive: 'Check whether a dialog conversation is currently open',
  isMusicPlaying: 'Check whether a music track is currently playing',
  isPaused: 'Check whether the game is currently paused',
  isOffScreen: 'Check whether the object is outside the camera view',
}

const ACTION_DESCRIPTIONS: Record<LogicActionType, string> = {
  setPause: 'Pause, resume, or toggle gameplay (time stops; input still works)',
  modifyVariable: 'Change a variable: set, add, subtract, multiply or divide (global or per-object)',
  setVariable: 'Set a variable to a value',
  addVariable: 'Add an amount to a variable',
  setPosition: 'Teleport the object to x, y',
  setVelocity: 'Set the horizontal and vertical velocity directly',
  playSound: 'Play a one-shot sound effect',
  playMusic: 'Start a music track',
  stopAllAudio: 'Stop every sound and music',
  controlMusic: 'Stop, pause, or resume the music track',
  setText: 'Change the Text label — bind a variable to show live values',
  setTextColor: 'Change the Text label color',
  setVolume: 'Change the master, music, or sound-effects volume',
  fadeMusic: 'Fade the music to a volume over time (fading to 0 stops it)',
  destroyEntity: 'Remove the object from the scene',
  clickToDestroy: 'Destroy the object when clicked',
  spawnEntity: 'Create a new object instance',
  spawnEntityAtPointer: 'Create an object at the mouse position',
  moveInDirection: 'Set velocity in a direction at a given speed',
  controllerMovement: 'Move in this direction only while the rule is active',
  moveController: 'Keep moving in this direction until another rule changes it',
  clearMovementIntent: 'Stop the controller from moving',
  requestPlatformerJump: 'Jump if the body is grounded',
  setPlatformerMaxSpeed: 'Change the platformer run speed',
  setPlatformerJumpForce: 'Change the platformer jump strength',
  setPlatformerGravity: 'Change the platformer custom gravity',
  setTopDownMaxSpeed: 'Change the top-down movement speed',
  setTopDownAcceleration: 'Change how quickly the top-down controller speeds up',
  setTopDownFriction: 'Change how quickly the top-down controller slows down',
  setTopDownFourDirections: 'Constrain top-down movement to one axis at a time',
  damageEntity: 'Subtract health from the object',
  healEntity: 'Restore health to the object',
  setEntityHealth: 'Set health to an exact value',
  setLinearMoverDirection: 'Change the linear mover direction',
  setLinearMoverSpeed: 'Change the linear mover speed',
  pauseLinearMover: 'Pause the linear mover',
  resumeLinearMover: 'Resume the linear mover',
  setMagnetEnabled: 'Turn the magnet component on or off',
  setMagnetTargetTag: 'Change which tag the magnet attracts',
  setMagnetRadius: 'Change how far the magnet searches for targets',
  setMagnetPullSpeed: 'Change how quickly targets are pulled toward the magnet',
  setHordeTargetClass: 'Change which object type the horde chases',
  setHordeWeights: 'Tune the horde steering weights',
  setHordeMaxSpeed: 'Change the maximum horde movement speed',
  setHordeSeparationRadius: 'Change the distance used to keep horde members apart',
  setAutoDestroyLifespan: 'Destroy the object after N seconds',
  cancelAutoDestroy: 'Cancel a pending auto destroy',
  emitEvent: 'Broadcast an Event Bus event to other rules',
  toggleLogicEvent: 'Enable or disable another rule',
  applyImpulse: 'One-time physics push (jump, knockback)',
  applyForce: 'Continuous physics push while active',
  setRotation: 'Set the rotation angle',
  setScale: 'Set the size multiplier',
  playAnimation: 'Play an animation clip',
  setFlip: 'Mirror the sprite horizontally or vertically',
  setVisible: 'Show or hide the sprite',
  setColorTint: 'Tint the sprite with a color',
  loadScene: 'Switch to another scene',
  restartScene: 'Reload the current scene',
  centerCameraOn: 'Move the camera once so an object is centered',
  followCamera: 'Continuously center the camera on an object until changed or stopped',
  stopCameraFollow: 'Keep the camera at its current position and disable automatic follow',
  useDefaultCameraTarget: 'Resume the deterministic Camera Target component in the active scene',
  setCameraTarget: 'Legacy name: center the camera on an object once',
  cameraShake: 'Shake the camera briefly',
  debugLog: 'Print a message to the console',
  wait: 'Pause this rule for N seconds',
  repeatTimes: 'Run the next actions N times',
  moveByOffset: 'Nudge the object by pixels',
  snapToGrid: 'Align the object to the grid',
  setEntityShader: 'Apply a visual effect to this object',
  setScreenShader: 'Apply a full-screen visual effect',
  startDialog: 'Open a dialog from the target Dialog component, or choose a specific dialog asset',
  endDialog: 'Close the currently active dialog conversation',
  saveGame: 'Persist all declared global and placed-object variables',
  loadGame: 'Restore all declared global and placed-object variables',
  deleteSave: 'Delete an entire save slot from disk',
  setCameraZoom: 'Set the camera zoom level (1 = normal)',
  panCamera: 'Shift the camera by a pixel offset',
  setCameraPosition: 'Set the world point shown at the screen top-left corner',
  setTimeScale: 'Control game speed (0 = pause, 0.5 = slow-mo, 1 = normal)',
  spawnAtEntity: 'Create a new object at another object\'s current position',
  moveToward: 'Move toward another object at a given speed',
  lookAtTarget: 'Rotate to face another object',
}

export function typeDescription(kind: ComponentKind, type: string): string | undefined {
  if (kind === 'trigger') return TRIGGER_DESCRIPTIONS[type as LogicTriggerType]
  if (kind === 'action') return ACTION_DESCRIPTIONS[type as LogicActionType]
  return CONDITION_DESCRIPTIONS[type as LogicCondition['type']]
}
