import type {
  LogicActionType,
  LogicCondition,
  LogicTriggerType,
} from '../../../types/logic-board'

const TRIGGER_NAMES: Record<LogicTriggerType, string> = {
  onStart: 'Game starts',
  onSpawn: 'Object is created',
  onUpdate: 'Every frame',
  onCollision: 'While touching type',
  onCollisionEnter: 'Starts touching type',
  onCollisionExit: 'Stops touching type',
  onTriggerEnter: 'Enters sensor zone',
  onTriggerExit: 'Leaves sensor zone',
  onAnimationEnd: 'Animation finishes',
  onAnimationStart: 'Animation starts',
  onAnimationFrame: 'Animation reaches frame',
  onAnimationLoop: 'Animation loops',
  onAnimationChange: 'Animation changes',
  onDestroy: 'Object is destroyed',
  onHealthDepleted: 'Health reaches zero',
  onDamaged: 'Takes damage',
  onInput: 'Keyboard key',
  onMouseInput: 'Mouse button',
  onObjectClick: 'Object clicked',
  onObjectHoverEnter: 'Pointer enters object',
  onObjectHoverExit: 'Pointer leaves object',
  onMessage: 'Game message',
  onTimer: 'Timer',
  onLeaveScreen: 'Leaves the screen',
}

const ACTION_NAMES: Record<LogicActionType, string> = {
  setPause: 'Pause / resume game',
  modifyVariable: 'Modify variable',
  setVariable: 'Set variable',
  addVariable: 'Add to variable',
  setPosition: 'Teleport to position',
  setVelocity: 'Set velocity X and Y',
  playSound: 'Play sound',
  playMusic: 'Play music',
  stopAllAudio: 'Stop all audio',
  setText: 'Set text',
  setTextColor: 'Text color',
  setVolume: 'Set volume',
  fadeMusic: 'Fade music',
  controlMusic: 'Control music',
  destroyEntity: 'Destroy object',
  clickToDestroy: 'Click to destroy',
  spawnEntity: 'Create object',
  spawnEntityAtPointer: 'Create at pointer',
  moveInDirection: 'Set velocity in direction',
  controllerMovement: 'Set direction',
  moveController: 'Set fixed direction',
  clearMovementIntent: 'Stop moving',
  requestPlatformerJump: 'Platformer jump',
  setPlatformerMaxSpeed: 'Platformer max speed',
  setPlatformerJumpForce: 'Platformer jump force',
  setPlatformerGravity: 'Platformer gravity',
  setTopDownMaxSpeed: 'Top-down max speed',
  setTopDownAcceleration: 'Top-down acceleration',
  setTopDownFriction: 'Top-down friction',
  setTopDownFourDirections: 'Top-down 4-directions',
  damageEntity: 'Damage',
  healEntity: 'Heal',
  setEntityHealth: 'Set health',
  setLinearMoverDirection: 'Linear mover direction',
  setLinearMoverSpeed: 'Linear mover speed',
  pauseLinearMover: 'Pause linear mover',
  resumeLinearMover: 'Resume linear mover',
  setMagnetEnabled: 'Magnet on/off',
  setMagnetTargetTag: 'Magnet tag',
  setMagnetRadius: 'Magnet radius',
  setMagnetPullSpeed: 'Magnet pull speed',
  setHordeTargetClass: 'Horde chase class',
  setHordeWeights: 'Horde weights',
  setHordeMaxSpeed: 'Horde max speed',
  setHordeSeparationRadius: 'Horde separation radius',
  setAutoDestroyLifespan: 'Auto destroy timer',
  cancelAutoDestroy: 'Cancel auto destroy',
  emitEvent: 'Send message',
  toggleLogicEvent: 'Turn rule on/off',
  applyImpulse: 'Jump or push',
  applyForce: 'Push steadily',
  setRotation: 'Rotate',
  setScale: 'Set scale',
  playAnimation: 'Play animation',
  setFlip: 'Flip',
  setVisible: 'Show or hide',
  setColorTint: 'Change color',
  loadScene: 'Load level',
  restartScene: 'Restart level',
  centerCameraOn: 'Center camera on object',
  followCamera: 'Follow object with camera',
  stopCameraFollow: 'Stop camera follow',
  useDefaultCameraTarget: 'Automatic camera follow',
  setCameraTarget: 'Center camera on object — legacy',
  cameraShake: 'Camera shake',
  debugLog: 'Debug message',
  wait: 'Wait',
  repeatTimes: 'Repeat',
  moveByOffset: 'Nudge by offset',
  snapToGrid: 'Snap entity to grid (runtime)',
  setEntityShader: 'Visual effect on object',
  setScreenShader: 'Screen effect',
  startDialog: 'Start dialog by ID',
  endDialog: 'End active dialog',
  saveGame: 'Save game',
  loadGame: 'Load game',
  deleteSave: 'Delete save slot',
  setCameraZoom: 'Set camera zoom',
  panCamera: 'Pan camera',
  setCameraPosition: 'Set camera position',
  setTimeScale: 'Set time scale',
  spawnAtEntity: 'Create at object',
  moveToward: 'Move toward object',
  lookAtTarget: 'Rotate to face object',
}

const CONDITION_NAMES: Record<LogicCondition['type'], string> = {
  compareVariable: 'Variable check',
  compareValues: 'Compare values',
  compareClass: 'Touching type',
  isKeyDown: 'Key held',
  hasTag: 'Has tag',
  compareDistance: 'Distance check',
  isMouseOver: 'Mouse nearby',
  raycastHit: 'Line of sight',
  chance: 'Random chance',
  isTileAreaFree: 'Tile area is free',
  isSpaceFree: 'Area is free — legacy',
  compareHealth: 'Health check',
  isPlatformerGrounded: 'On ground',
  compareCount: 'Object count',
  entityExists: 'Object exists',
  compareVelocity: 'Velocity check',
  comparePosition: 'Position check',
  saveExists: 'Save file exists',
  isDialogActive: 'Dialog is active',
  isMusicPlaying: 'Music is playing',
  isPaused: 'Game is paused',
  isOffScreen: 'Is off screen',
}

export function triggerDisplayName(type: LogicTriggerType): string {
  return TRIGGER_NAMES[type] ?? type
}

export function actionDisplayName(type: LogicActionType): string {
  return ACTION_NAMES[type] ?? type
}

export function conditionDisplayName(type: LogicCondition['type']): string {
  return CONDITION_NAMES[type] ?? type
}
