// ---------------------------------------------------------------------------
// Compiler scaffolding — the fixed Lua templates wrapped around the per-board
// emit output:
//
//   • buildHeader:           emits the script-top block. Three concerns:
//                             1) Hot-reload unsub tracking: __artcade_lb_unsubs
//                                global + _logic_track / _logic_bag_unsub /
//                                _logic_reg_* helpers that revoke handlers
//                                registered by the previous compile.
//                             2) One-time locals (timers, enable flags, RULE
//                                alias table, _mb mouse edge state, movement
//                                frame helpers).
//                             3) Project-tick capture (__artcade_project_tick
//                                / __artcade_board_active globals).
//   • SENSOR_POLL_PREAMBLE:  builds _sensor_by_ent at the top of each tick
//                            when any tick-fallback sensor event is present.
//   • DESTROY_POLL_PREAMBLE: drains lifecycle.pollDestroyed() the same way.
//   • buildTickWrapper:      wraps the per-board tick blocks with the
//                            standard init guard + movement flush.
// ---------------------------------------------------------------------------

import { INDENT, luaString } from './lua-helpers'
import { RULE_TABLE } from './event-slugs'

/** Header lines emitted once at the top of every compiled board script. */
export function buildHeader(eventSlugs: Map<string, string>): string[] {
  const ruleEntries: string[] = []
  for (const [id, slug] of eventSlugs) {
    ruleEntries.push(`${INDENT}${slug} = ${luaString(id)},`)
  }

  return [
    '-- AUTO-GENERATED by ArtCade Logic Board compiler.',
    '-- Do not edit by hand: changes will be overwritten on next save.',
    '',
    '-- Revoke handlers registered by the previous compile of this Logic Board',
    '-- so hot reloads do not stack duplicates on the runtime dispatchers.',
    '-- User-authored handlers (registered from main.lua etc.) are untouched.',
    '__artcade_lb_unsubs = __artcade_lb_unsubs or {}',
    'for i = #__artcade_lb_unsubs, 1, -1 do',
    `${INDENT}local _ok, _err = pcall(__artcade_lb_unsubs[i])`,
    `${INDENT}if not _ok then debug.log("[logic] unsub error: " .. tostring(_err)) end`,
    'end',
    '__artcade_lb_unsubs = {}',
    '',
    'local function _logic_track(unsub)',
    `${INDENT}if type(unsub) == "function" then`,
    `${INDENT}${INDENT}__artcade_lb_unsubs[#__artcade_lb_unsubs + 1] = unsub`,
    `${INDENT}end`,
    'end',
    '',
    '-- Remove a specific closure from a {key = {fn, fn, ...}} bag (lifecycle,',
    '-- sensor, input, animation). Cheap linear scan — bags are tiny.',
    'local function _logic_bag_unsub(bag, key, fn)',
    `${INDENT}return function()`,
    `${INDENT}${INDENT}if type(bag) ~= "table" then return end`,
    `${INDENT}${INDENT}local list = bag[key]`,
    `${INDENT}${INDENT}if type(list) ~= "table" then return end`,
    `${INDENT}${INDENT}for i = #list, 1, -1 do`,
    `${INDENT}${INDENT}${INDENT}if list[i] == fn then table.remove(list, i); return end`,
    `${INDENT}${INDENT}end`,
    `${INDENT}end`,
    'end',
    '',
    '-- Sensor/animation bags key by source + "\\31" + target. Mirror the runtime.',
    'local function _logic_compose_key(source, target)',
    `${INDENT}return tostring(source or "*") .. "\\31" .. tostring(target or "*")`,
    'end',
    '',
    'local function _logic_reg_spawn(cls, fn)',
    `${INDENT}lifecycle.onSpawn(cls, fn)`,
    `${INDENT}_logic_track(_logic_bag_unsub(lifecycle._onSpawn, cls, fn))`,
    'end',
    '',
    'local function _logic_reg_destroy(cls, fn)',
    `${INDENT}lifecycle.onDestroy(cls, fn)`,
    `${INDENT}_logic_track(_logic_bag_unsub(lifecycle._onDestroy, cls, fn))`,
    'end',
    '',
    'local function _logic_reg_anim_end(source, clip, fn)',
    `${INDENT}animation.onFinished(source, clip, fn)`,
    `${INDENT}_logic_track(_logic_bag_unsub(animation._onFinished, _logic_compose_key(source, clip), fn))`,
    'end',
    '',
    'local function _logic_reg_input_pressed(code, fn)',
    `${INDENT}input.onPressed(code, fn)`,
    `${INDENT}_logic_track(_logic_bag_unsub(input._onPressed, code, fn))`,
    'end',
    '',
    'local function _logic_reg_input_released(code, fn)',
    `${INDENT}input.onReleased(code, fn)`,
    `${INDENT}_logic_track(_logic_bag_unsub(input._onReleased, code, fn))`,
    'end',
    '',
    'local function _logic_reg_sensor_enter(source, target, fn)',
    `${INDENT}sensor.onEnter(source, target, fn)`,
    `${INDENT}_logic_track(_logic_bag_unsub(sensor._onEnter, _logic_compose_key(source, target), fn))`,
    'end',
    '',
    'local function _logic_reg_sensor_exit(source, target, fn)',
    `${INDENT}sensor.onExit(source, target, fn)`,
    `${INDENT}_logic_track(_logic_bag_unsub(sensor._onExit, _logic_compose_key(source, target), fn))`,
    'end',
    '',
    'local function _logic_reg_message(name, fn)',
    `${INDENT}_logic_track(event.on(name, fn))`,
    'end',
    '',
    'local function _logic_reg_timer_every(seconds, fn)',
    `${INDENT}_logic_track(time.every(seconds, fn))`,
    'end',
    '',
    "-- time.after / time.delay are one-shot and self-clean on fire; we still",
    '-- guard hot-reload double-fire by checking a per-compile gate token.',
    'local function _logic_reg_timer_after(seconds, fn)',
    `${INDENT}local gate = __artcade_lb_unsubs`,
    `${INDENT}time.after(seconds, function()`,
    `${INDENT}${INDENT}if __artcade_lb_unsubs ~= gate then return end`,
    `${INDENT}${INDENT}fn()`,
    `${INDENT}end)`,
    'end',
    '',
    'local _init_done = false',
    'local _logic_timers = {}   -- polling timers',
    'local _logic_on = {}       -- event enable flags',
    // RULE is always declared so any `RULE.<slug>` reference emitted by
    // ruleKeyExpr resolves to a valid binding, even if buildEventSlugs
    // ever returns an empty map. Empty literal is valid Lua.
    '-- Readable aliases for rule ids — used as keys into _logic_on.',
    ...(ruleEntries.length > 0
      ? [`local ${RULE_TABLE} = {`, ...ruleEntries, '}']
      : [`local ${RULE_TABLE} = {}`]),
    'local _mb = {}             -- mouse button edge state',
    'local _logic_movement_known = {}',
    'local _logic_movement_frame = nil',
    '',
    'local function _logic_add_movement(entityId, x, y)',
    `${INDENT}if _logic_movement_frame == nil or entityId == nil then return end`,
    `${INDENT}local m = _logic_movement_frame[entityId]`,
    `${INDENT}if not m then`,
    `${INDENT}${INDENT}m = { x = 0, y = 0 }`,
    `${INDENT}${INDENT}_logic_movement_frame[entityId] = m`,
    `${INDENT}end`,
    `${INDENT}m.x = m.x + x`,
    `${INDENT}m.y = m.y + y`,
    'end',
    '',
    'local function _logic_flush_movement()',
    `${INDENT}if _logic_movement_frame == nil then return end`,
    `${INDENT}for entityId, m in pairs(_logic_movement_frame) do`,
    `${INDENT}${INDENT}if m.x ~= 0 or m.y ~= 0 then`,
    `${INDENT}${INDENT}${INDENT}movement.setIntent(entityId, m.x, m.y)`,
    `${INDENT}${INDENT}else`,
    `${INDENT}${INDENT}${INDENT}movement.clearIntent(entityId)`,
    `${INDENT}${INDENT}end`,
    `${INDENT}${INDENT}_logic_movement_known[entityId] = true`,
    `${INDENT}end`,
    `${INDENT}for entityId, _ in pairs(_logic_movement_known) do`,
    `${INDENT}${INDENT}if _logic_movement_frame[entityId] == nil then`,
    `${INDENT}${INDENT}${INDENT}movement.clearIntent(entityId)`,
    `${INDENT}${INDENT}${INDENT}_logic_movement_known[entityId] = nil`,
    `${INDENT}${INDENT}end`,
    `${INDENT}end`,
    `${INDENT}_logic_movement_frame = nil`,
    'end',
    '',
    "-- Keep the project's own tick(dt) and layer Logic Board behavior on top.",
    '-- Hot reload replaces the global tick(), so the original project tick is',
    '-- captured once and reused across repeated Apply operations.',
    'if __artcade_project_tick == nil and not __artcade_board_active then',
    `${INDENT}__artcade_project_tick = rawget(_G, "tick")`,
    'end',
    '__artcade_board_active = true',
    '',
  ]
}

export const SENSOR_POLL_PREAMBLE = [
  `${INDENT}local _sensor_by_ent = {}`,
  `${INDENT}for _, se in ipairs(sensor.poll()) do`,
  `${INDENT}${INDENT}local eid = se.entityId`,
  `${INDENT}${INDENT}if not _sensor_by_ent[eid] then _sensor_by_ent[eid] = {} end`,
  `${INDENT}${INDENT}table.insert(_sensor_by_ent[eid], se)`,
  `${INDENT}end`,
]

export const DESTROY_POLL_PREAMBLE = [
  `-- Fallback when onDestroy has no board class (prefer lifecycle.onDestroy in init)`,
  `${INDENT}local _destroy_events = lifecycle.pollDestroyed()`,
]

/**
 * Build the `tick(dt)` function body that wraps the per-board tick blocks
 * with init guard, movement frame setup, optional poll preambles, and the
 * final movement flush.
 */
export function buildTickWrapper(args: {
  tickBlocks: string[]
  hasPollingLogic: boolean
  useSensor: boolean
  useDestroy: boolean
  initBlocks: string[]
}): string[] {
  const { tickBlocks, hasPollingLogic, useSensor, useDestroy, initBlocks } = args
  return [
    'local function _logic_init()',
    ...initBlocks,
    'end',
    '',
    `__artcade_requires_tick = ${hasPollingLogic ? 'true' : 'false'} or (__artcade_project_tick ~= nil)`,
    'if not __artcade_requires_tick and not _init_done then',
    `${INDENT}_logic_init()`,
    `${INDENT}_init_done = true`,
    'end',
    '',
    'function tick(dt)',
    `${INDENT}-- Run the project's own game logic first.`,
    `${INDENT}if __artcade_project_tick then __artcade_project_tick(dt) end`,
    `${INDENT}if not _init_done then`,
    `${INDENT}${INDENT}_logic_init()`,
    `${INDENT}${INDENT}_init_done = true`,
    `${INDENT}end`,
    `${INDENT}_logic_movement_frame = {}`,
    ...(useSensor ? SENSOR_POLL_PREAMBLE : []),
    ...(useDestroy ? DESTROY_POLL_PREAMBLE : []),
    ...tickBlocks,
    `${INDENT}_logic_flush_movement()`,
    'end',
    '',
  ]
}
