const BOARD_MARKER = /^\s*-- board: .+$/
const STOP_AFTER_BOARD = /^\s*(?:_init_done = true|module\.requiresTick|function module\.|end\)\(\))/
const GUARD_LINE = /^(\s*)if _logic_on\[.+\] ~= false then$/
const END_LINE = /^(\s*)end$/

function leadingSpaces(line: string): number {
  const match = line.match(/^ */)
  return match?.[0].length ?? 0
}

function stripOneIndent(line: string): string {
  return line.startsWith('  ') ? line.slice(2) : line
}

function rewriteRuntimeHelpers(line: string): string {
  return line
    .replace('_logic_reg_input_pressed(', 'input.onPressed(')
    .replace('_logic_reg_input_released(', 'input.onReleased(')
    .replace('_logic_reg_message(', 'event.on(')
    .replace('_logic_reg_timer_every(', 'time.every(')
    .replace('_logic_reg_timer_after(', 'time.after(')
    .replace('_logic_reg_spawn(', 'lifecycle.onSpawn(')
    .replace('_logic_reg_destroy(', 'lifecycle.onDestroy(')
    .replace('_logic_reg_anim_end(', 'animation.onFinished(')
    .replace('_logic_reg_anim_start(', 'animation.onStart(')
    .replace('_logic_reg_anim_frame(', 'animation.onFrame(')
    .replace('_logic_reg_anim_loop(', 'animation.onLoop(')
    .replace('_logic_reg_anim_change(', 'animation.onChanged(')
    .replace('_logic_reg_sensor_enter(', 'sensor.onEnter(')
    .replace('_logic_reg_sensor_exit(', 'sensor.onExit(')
}

function extractBoardChunks(lua: string): string[][] {
  const lines = lua.split('\n')
  const chunks: string[][] = []
  let current: string[] | null = null

  for (const line of lines) {
    if (BOARD_MARKER.test(line)) {
      if (current && current.length > 0) chunks.push(current)
      current = [line]
      continue
    }

    if (!current) continue
    if (BOARD_MARKER.test(line) || STOP_AFTER_BOARD.test(line)) {
      chunks.push(current)
      current = null
      continue
    }
    if (line === 'end') {
      chunks.push(current)
      current = null
      continue
    }
    current.push(line)
  }

  if (current && current.length > 0) chunks.push(current)
  return chunks
}

function removeInternalGuard(lines: string[]): string[] {
  const out: string[] = []
  let guardIndent: number | null = null

  for (const line of lines) {
    const guard = line.match(GUARD_LINE)
    if (guard) {
      guardIndent = guard[1].length
      continue
    }

    if (guardIndent !== null) {
      const end = line.match(END_LINE)
      if (end && end[1].length === guardIndent) {
        guardIndent = null
        continue
      }
      if (leadingSpaces(line) > guardIndent) {
        out.push(stripOneIndent(line))
        continue
      }
    }

    out.push(line)
  }

  return out
}

function formatChunk(lines: string[]): string {
  return removeInternalGuard(lines)
    .filter((line) => line.trim() !== 'local other = nil')
    .map((line) => stripOneIndent(rewriteRuntimeHelpers(line)))
    .join('\n')
    .trimEnd()
}

/**
 * Return a read-only authoring view of compiled Logic Board Lua. Runtime-only
 * scaffolding stays in the real compiled source used by preview/build.
 */
export function formatGeneratedLogicLuaPreview(lua: string): string {
  const chunks = extractBoardChunks(lua)
    .map(formatChunk)
    .filter((chunk) => chunk.trim().length > 0)

  if (chunks.length === 0) return lua

  return [
    '-- AUTO-GENERATED by ArtCade Logic Board compiler.',
    '-- Read-only authoring preview. Runtime scaffolding is hidden.',
    '',
    chunks.join('\n\n'),
  ].join('\n')
}
